// <auto-generated />
namespace ProximaFase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class alter_console : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(alter_console));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141829055_alter_console"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
