// <auto-generated />
namespace ProximaFase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_combinacao_mensagens : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_combinacao_mensagens));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141750433_add_combinacao_mensagens"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
