// <auto-generated />
namespace ProximaFase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_remove_posts_categoria_comentario_categoria : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_remove_posts_categoria_comentario_categoria));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141716159_add_remove_posts_categoria_comentario_categoria"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
