// <auto-generated />
namespace ProximaFase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class jogoDesejadoModel_e_jogoPossuidoModel_correcao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(jogoDesejadoModel_e_jogoPossuidoModel_correcao));
        
        string IMigrationMetadata.Id
        {
            get { return "201612161916283_jogoDesejadoModel_e_jogoPossuidoModel_correcao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
