// <auto-generated />
namespace ProximaFase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_correcao_combinacao1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_correcao_combinacao1));
        
        string IMigrationMetadata.Id
        {
            get { return "201612190419298_add_correcao_combinacao1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
