// <auto-generated />
namespace ProximaFase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_cartao_de_credito : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_cartao_de_credito));
        
        string IMigrationMetadata.Id
        {
            get { return "201612141712156_add_cartao_de_credito"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
