// <auto-generated />
namespace ProximaFase.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class correcao_combinacao_include_usuariosEnvolvidos : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(correcao_combinacao_include_usuariosEnvolvidos));
        
        string IMigrationMetadata.Id
        {
            get { return "201612191606421_correcao_combinacao_include_usuariosEnvolvidos"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
